### ISSUE TITLE
Sonny "The Snail"

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#152]
Reported By: Vlad Bishop
Category: QUEST

I am on part 4 I believe, and there is a point where I have to talk to Sonny at lvl 30.  I am currnetly lvl 40 and cannot complete the quest it is telling me that I do not have the required items in my backpack.  In the quest description is says nothing of inventory needed.  What am I missing?  Thank you for your help.

Vlad

**Comment by LiskaQuicksilver** [comment]
Having talked to Vlad, I might have isolated the issue. For whatever reason, after collecting the 50 Magic Essences, Vlad went to turn in the quest but forgot to grab the Ring from his vault. The quest is not supposed to do anything unless both the Ring and the Essences are present, yet it seems the quest took his Essences and claimed it was 'complete' even though the Ring was not present and did not get updated to the next version. Due to this, he still has the old ring and a quest he cannot actually finish since the Ring did not update with the quest.

Since the quest is supposed to give the player a 'you do not have the required items to complete the quest' error when either the Ring, all 50 Magic Essences or neither one are present, yet it did not in this case and even took Vlad's Essences when his Ring was not present, I believe this is the bug Vlad has stumbled on. It's forcing him to reacquire the Essences all over again. If I am correct on this, we might want to fix this as soon as possible as such a bug will be a HUGE inconvenience to players as it is hard enough to gather the Essences for the quest as it is.

**Comment by rockfireredmoon** [comment]
I have tested this myself now and it does seem to work as expected. However, I have made some changes so that the count and description of the item is displayed in the error message. The quest START text does say whats needed, but the complete text doesn't, so unless you look in the journal you won't see it. This may be the reason for the original report.
