### ISSUE TITLE
Multiple Pawl at Trailblazers

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#406]
Reported By: Lazarus Lightscale
Category: MOB

For some reason, when I arrived at the Trailblazer logging area for my quest today, there were 3 copies of the named "Pawl" pathing in the camp. If I recall correctly, there should only be one instance of him at a time.

**Comment by LiskaQuicksilver** [comment]
Okay. I can confirm this bug even though Aureus provided a screenshot of this issue on Discord at the time of his report I have finally gotten around to testing this issue and have been able to replicate it. As I began to suspect while testing, it would seems that both Pawl and Babe the Blue have the same problem in fact. The issue is this: As Pawl was set to spawn after a certain number of regular Trailblazer mobs are defeated and Babe the Blue was set to spawn when Pawl is defeated, the game is freely spawning both based on the number of times both are spawned.

What is happening with Pawl is that when his 'x number of mobs killed to spawn' condition reaches that number, rather than halting the counter, it's returning to 0 and counting up again each time an additional Trailblazer mob is killed after his initial spawn. This is resulting in multiple Pawls being spawned at the same time provided the required number keeps being reached. Additionally, with each of these Pawls defeated, Babe the Blue will spawn for every single Pawl that is currently spawned. So, if 2 Pawls are spawned, then 2 Babes will spawn when they are defeated. If 3 Pawls get spawned, then 3 Babes will be spawned when each of those are eliminated.

Aureus suspects that neither Pawl nor Babe were given the 'unique spawn' flag so the game continues to spawn them both as per their spawn conditions irregardless of a previous instance of the mob existing on the field or not. If this is the case, it should be a rather easy fix.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Okay, this appears to be fixed, although I see you set Pawl to spawn at only 5 Trailblazers killed instead of whatever the number is needed for the quest objective. Minor nitpick here really, but, least neither Pawl nor Babe are multi-spawning anymore.

**Comment by rockfireredmoon** [comment]
I double checked, it appears it's always been 5. While the kill count is 20, the act text says "Pawl may only show himself when enough of his Trailblazer minions have been defeated. ".
