### ISSUE TITLE
Lore book pages

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#416]
Reported By: Thecrimson Bloodwolf
Category: ECON

After getting a page and leaving where you found it you are no longer able to read the page. Double Clicking on a page in the bookshelf does nothing and putting a page from the bookshelf back into you backpack and the double clicking on it will give an error message of "Could not show book X, page X

**Comment by LiskaQuicksilver** [comment]
Tested both the Bookshelf issue and the returning a page to inventory issue myself. Unsure if the former is due to the Bookshelf possibly requiring a completely bound Book to be readable or if there's some issue bugging it. The latter issue shouldn't happen either. It's almost as if the server is 'losing' its memory of the books and pages in question if they are returned to a player's inventory from the Bookshelf.

**Comment by rockfireredmoon** [comment]
I cannot reproduce the issue of moving between the inventory and bookshelf, I suspect this may have already been fixed. However, when books were moved to the bookshelf they were no longer showing in the reading room. But we should retest on the test server.

Books will now show in the reading room if they are in either the inventory or the bookshelf.

**Comment by rockfireredmoon** [comment]
Seems there was more to do. All books are now tested except for Grimm Tales and Blood Keep. These will be fixed tomorrow.

**Comment by rockfireredmoon** [comment]
Grimm's Tales and Blood Keep Tome are now done. The problem with these two was caused by the fact the material items were not in numeric order. Have raised #433 to address this in the future.

**Comment by LiskaQuicksilver** [comment]
Confirmed fixed!
