### ISSUE TITLE
Goliath Ruins dungeon Entrance

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#418]
Reported By: Sharlexia Springpaw
Category: WORLD

I couldn't get in till I mashed jump and Right click

**Comment by LiskaQuicksilver** [comment]
This is an old issue and well known. While testing the fixes for the buff/timer bug, I decided to kill time by attempting to address this little annoyance to players. After fiddling with the interact creature for the entrance and it's spawn point a bit I think I "may" have fixed the issue or at least made it more manageable for players.

That said, players can still mess around and get behind the ouroboros (due to the interact creature's shape and size) if they tried. Would need to change the size of the interact creature itself to address that.

Feel free to test this to see if the alterations made are satisfactory.

**Comment by LiskaQuicksilver** [comment]
Fix works. Closing.
