### ISSUE TITLE
Nix's Storage Chest Not Openable/Examinable (Greenline Thicket/Great Forest)

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#457]
Reported By: Dax Orillion
Category: QUEST

I could be wrong, and it might be working as intended as I have not myself done a quest in question that involves a key for this one, but as most chests of this nature tend to at least let you have a peek in them regardless of key in hand or not, I have to wonder if this is bugged:  while left-clicking on the chest next to Nix Stormburne displays "Nix's Storage Chest," right-clicking, on the other hand, produces nothing - no menu of any kind for it's contents if any.

**Comment by LiskaQuicksilver** [comment]
Upon investigating, all the quests associated with the NPC Nix Stormbourne involve the Bileforge and the NPC camp near it. This chest is not mentioned or referenced. Because of this, I believe Nix's Storage Chest is quite likely an artifact from SPM's alpha quests as there are a number of lingering half-interactable assets in the game that once belonged to long defunct and discarded early quest ideas that were later scrapped.
