### ISSUE TITLE
Social Media announcements

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#75]
One of the final tasks, letting everyone know!

 * Decide on release day and stick to it!
 * Decide on whether we want an opening event (I personally think we should) and arrange said event
 * Complete the press release (needs screen shots, movie? and a more complete list of the new features). This should be moved to a non-private wiki area and will be provided to all interested groups somehow (either the complete content or links to the content with a sumarry).
 * Update the Facebook group "Earth Eternal Fans" with the news
 * Post on Terra Eternus
 * Mail shot to all known email addresses. Heath probably has some, and there is a list in the Wiki private area (http://armouree.vm.bytemark.co.uk/dokuwiki/doku.php?id=private:mainserverkeys). Emerald has a few players who asked for a block of registration keys, this is a good time to do so.
 * I was thinking we should set up a Twitter account for future announcements

**Comment by Heathendel** [comment]
I agree on all fronts you and i have spoken the last few days about our feelings on having the Scourge spark open beta but have a retool with the next update letting players know of the massive changes.

Players will be ecstatic to play but i think maybe we should announce it as a Closed Beta and that theyve all been given access for following our progress that way its more justifiable to wipe characters when we make the class and story update.

As soon as you think you can have the update ready Em i think you should set the release date.  Were already set up to run an event with those new mechanics you mentioned we can have combat events and social ones run by sages so whenever its ready for update i think that should be the release maybe a week from now? so lets say september 7th?


That being said im not crazy about the classic server idea.  splitting what will already be a small community is like shooting ourselves in the foot before a race we need all the players we can get and we need them on the same server.  Its been proven time and time again that players dont like the classic version because we have a near impossible time keeping players even playing it.  So having a classic server in my opinion is a waste of resources and will most likely have players play to lvl 8 then quit and not give the real server a chance because theyll come for the nostalgia get bored and think the main server has nothing to offer.  I'll back which ever way we choose to go but I cant stress enough how fragile our server will be population wise and urge you to look at the servers track record one more time and see if a classic server is necessary or if it will ultimately hurt us.

**Comment by rockfireredmoon** [comment]
Closing this, issues mentioned mostly resolved or are planned for.
